--- 
abstract: Ruby-like list operations
author: Naoya Ito, <naoya at hatena.ne.jp<gt>
build_requires: 
  FindBin::libs: 0
  Test::Class: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: List-RubyLike
no_index: 
  directory: 
    - inc
    - t
requires: 
  Exporter::Lite: 0
  List::MoreUtils: 0
  List::Util: 0
  perl: 5.8.1
version: 0.01
